version: '3'
services:
  twitterdb:
    image: "mongo"
    volumes:
      - ".db/mongodb/twitterdb:/data/db"
    ports:
      - "27017:27017"
    networks:
      - "twitter_network"

networks:
  twitter_network:
    driver: "bridge"
