version: '3'
services:
  twitterdb:
    image: "mongo"
    volumes:
      - ".db/mongodb/twitterdb:/data/db"
    ports:
      - "27017:27017"
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: admin
      # MONGO_INITDB_DATABASE: twitterapp
    networks:
      - "twitter_network"

networks:
  twitter_network:
    driver: "bridge"
